/**
 * Deterministic pseudo-randomness, seeded by a string.
 *
 * Draws are seeded per draw and the seed is written into the event, so a
 * disputed draw can be shown to have been fair. The stored chart list stays
 * authoritative — the seed exists so the list can be *checked*, not so it can
 * be regenerated by a future version of this file whose behaviour has drifted.
 *
 * The algorithms are pinned rather than chosen freshly: FNV-1a to fold the seed
 * string into 32 bits, then mulberry32 to expand it. Both are small, standard
 * and fully specified, which is what makes an audit reproducible at all. The
 * tests lock their output, so a change here fails loudly.
 */

/** FNV-1a, 32-bit. Folds an arbitrary seed string into a starting state. */
function fnv1a32(input: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

export interface Rng {
  /** A uniform integer in [0, bound). Throws if bound is not positive. */
  nextInt(bound: number): number;
}

/**
 * mulberry32. Chosen for being a handful of lines and completely specified —
 * an auditor can re-derive a draw from the seed without this package.
 */
export function makeRng(seed: string): Rng {
  let state = fnv1a32(seed);

  const nextUint32 = (): number => {
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return (t ^ (t >>> 14)) >>> 0;
  };

  return {
    nextInt(bound: number): number {
      if (!Number.isInteger(bound) || bound <= 0) {
        throw new RangeError(`nextInt bound must be a positive integer, got ${bound}`);
      }
      // Rejection sampling. Taking uint32 % bound directly would favour the
      // low residues whenever bound does not divide 2^32; at pack sizes the
      // bias is tiny, but it is free to remove and awkward to argue about
      // afterwards if a player disputes a draw.
      const limit = Math.floor(0x1_0000_0000 / bound) * bound;
      let x = nextUint32();
      while (x >= limit) x = nextUint32();
      return x % bound;
    },
  };
}
